name: Release and Build

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  release-and-pages:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_latest_release.outputs.latest_tag }}
    steps:
      # 1. Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - run: npm ci

      # 4. Run Semantic Release
      - name: Run Semantic Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release || echo "No release created"

      # 5. Deploy GitHub Pages
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # adjust if your index.html is elsewhere

      # 6. Get latest release tag via GitHub CLI
      - name: Get latest release
        id: get_latest_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(gh release list --repo $GITHUB_REPOSITORY --limit 1 --json tagName --jq '.[0].tagName')
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

  windows-build:
    runs-on: windows-latest
    needs: release-and-pages
    steps:
      # 1. Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build Windows app only if a release exists
      - name: Build Windows App
        if: needs.release-and-pages.outputs.latest_tag != ''
        run: npm run build:win

      # 5. Upload Windows Installer
      - name: Upload Windows Installer
        if: needs.release-and-pages.outputs.latest_tag != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.release-and-pages.outputs.latest_tag }}
          asset_path: dist/Texture Ripper Setup.exe
          asset_name: Texture-Ripper-Setup.exe
          asset_content_type: application/octet-stream

      # 6. Upload Windows ZIP
      - name: Upload Windows ZIP
        if: needs.release-and-pages.outputs.latest_tag != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.release-and-pages.outputs.latest_tag }}
          asset_path: dist/Texture-Ripper.zip
          asset_name: Texture-Ripper.zip
          asset_content_type: application/zip
